### ISSUE TITLE
Diagnostics API improvements

### ISSUE THREAD

**Issue by goto-bus-stop** [apollographql/apollo-rs#617]
I want to rework the apollo-compiler diagnostics a bit for better extensibility and programmatic use. This is sort of a tracking issue to document the goals of the improvements.

Key points:
- [ ] Define custom diagnostics: likely have a Diagnostic trait that users can implement https://github.com/apollographql/apollo-rs/issues/606
- [x] Fix our byte/character offset mismatch in ariadne https://github.com/zesterer/ariadne/issues/8
- [x] Expose line number / column information on labels, currently you just get index https://github.com/apollographql/apollo-rs/issues/607
- [x] Have some way to represent diagnostic labels **without** having a source location. This is relevant for sythetic documents.

Different formatting options:

- [x] a full CLI-style report with source code snippets (current), + support for no-color environments https://github.com/apollographql/apollo-rs/issues/499
- [x] a basic string message that can be used in HTTP responses or other more restricted environments to still give users all necessary info without being able to point to different parts of the code: `for d in diagnostics.iter() { println!("{}", d.message()) }`
- [x] JSON format compatible with graphQL HTTP error responses https://github.com/apollographql/apollo-rs/issues/423
- [ ] The plain string format and JSON format would likely use schema coordinates instead of pointing to things visually. 

I'm thinking of having an ApolloDiagnostic trait instead of an enum and maybe providing a `define_diagnostic!()` macro to easily create new implementations of this trait.

**Comment by SimonSapin** [comment]
In apollo-compiler v1.0 everything can be serialized with `Display` or `to_string`.

**Comment by lrlna** [comment]
@SimonSapin this issue had a lot more than just serialisation. all the other ones are also already done in v1.0?

**Comment by SimonSapin** [comment]
I think i meant this comment (and closing) for another issue but mixed up my browser tabs. Sorry!

**Comment by SimonSapin** [comment]
https://github.com/zesterer/ariadne/issues/8 is still open and relevant, but I’ve added a check mark above as we have a work around in https://github.com/apollographql/apollo-rs/pull/668 for 0.11 and https://github.com/apollographql/apollo-rs/pull/698 for 1.0.

Ariadne labels are inherently associated with a location. The pattern started in compiler 1.0 (but not yet applied consistently) is that we skip labels when location is missing. So essential information should be in the main message (which is shown unconditionally).

**Comment by goto-bus-stop** [comment]
Since custom diagnostics are not going to end up having any features in apollo-rs, and the rest is done, will close this in favour of https://github.com/apollographql/apollo-rs/issues/756 which is the upcoming work to migrate to #747.
