### ISSUE TITLE
apollo-compiler@0.12.0 checklist

### ISSUE THREAD

**Issue by lrlna** [apollographql/apollo-rs#641]
- [ ] validation on top of current data structure
- [ ] set_type_system_hir
- [ ] remove `hir` module
- [ ] adding to the test suite with old `hir` to test the new `hir`
- [ ] port the router to the new APIs
- [ ] run on the schema corpus
- [ ] docs for the new architecture
- [ ] docs for new API usage (rust inline docs + readme)
- [ ] more examples:
  - [ ] operation manipulations
  - [ ] synthetic/logic based schema creation (only merge specific fields in an object type)
  - [ ] create a schema and use that as set_type_system_hir to start a compiler

**Comment by SimonSapin** [comment]
> set_type_system_hir

Similarly, users may want to validate a programatically-created `ExecutableDocument` without serializing and re-parsing it. So we’d need a naming scheme for all four combinations of adding input to a compiler, on two axes:

* A string to be parsed v.s. a high-level data structure
* Schema v.s. executable

(Plus one for a mixed schema-and-executable string to be parsed, though there’s no data structure equivalent)
