### ISSUE TITLE
typed ast: parse graphql types

### ISSUE THREAD

**Issue by lrlna** [apollographql/apollo-rs#8]
using generated nodes from #3 and syntax kinds from #2 we need to be able to create parse rules for the following graphql types:

- [x] #9
- [x] #10
- [x] #11
- [x] #12
    - [x] #13
    - [x] parse OperationDefinition
    - [x] #44
- [x] #20
    - [x] parse InlineFragment
    - [x] parse FragmentDefinition
    - [x] parse FragmentName
- [x] #21
- [x] #22
    - [x] #23
    - [x] #24
    - [x] #25
    - [x] #26
    - [x] #27
    - [x] #28
    - [x] #29
    - [x] #30
- [x] #31
- [x] #32
- [x] #33
- [x] #34
- [x] #35
- [x] #36
- [x] #37
- [x] #38
- [x] #39
- [x] #40
- [x] #42
- [x] #41
- [x] #43
- [x] #45
- [x] #46
- [x] #47
- [x] #48
    - [x] parse ScalarTypeDefinition
    - [x] parse ScalarTypeExtension
- [x] #49
- [x] #50
- [x] #51
- [x] #52
    - [x] #14
    - [x] #15
    - [x] #16
    - [x] #17
    - [x] #18
    - [x] #19
    - [x] #68 
    - [x] #68 
- [x] #53
    - [x] parse InterfaceTypeDefinition
    - [x] parse InterfaceTypeExtension
- [x] #54
    - [x] parse UnionTypeDefinition
    - [x] parse UnionMemberTypes
    - [x] parse UnionTypeExtension
- [x] #55
    - [x] parse EnumTypeDefinition
    - [x] parse EnumValuesDefinition
    - [x] parse EnumValueDefinition
    - [x] parse EnumTypeExtension
- [x] #56
    - [x] parse ArgumentsDefinition
    - [x] parse InputValueDefinition
    - [x] parse InputObjectTypeDefinition
    - [x] parse InputFieldsDefinition
    - [x] parse InputObjectTypeExtension
- [x] #57
    - [x] parse Directives
    - [x] parse Directive
    - [x] parse DirectiveDefinition
    - [x] parse DirectiveLocations
    - [x] parse DirectiveLocation
    - [x] parse ExecutableDirectiveLocation
    - [x] parse TypeSystemDirectiveLocation
 - [x] parse whitespace and other ignored tokens apollographql/apollo-rs#79
 - [x] apollographql/apollo-rs#72
 - [x] apollographql/apollo-rs#71
 - [x] apollographql/apollo-rs#83
