### ISSUE TITLE
smith: generate a federation supergraph with @link

### ISSUE THREAD

**Issue by lrlna** [apollographql/apollo-rs#806]
A progressive list of federation directives `apollo-smith` should add and generate to create a supergraph:

``` tasklist
# Tasks
- [ ] `@link` directive on schem definition pointing to `https://specs.apollo.dev/link/v1.0`
- [ ] `import` argument for `@link` https://specs.apollo.dev/link/v1.0/#@link.import
- [ ] `as` argument for `@link` https://specs.apollo.dev/link/v1.0/#@link.as
- [ ] `url` argument for `@link` https://specs.apollo.dev/link/v1.0/#@link.url
- [ ] use arbitrary to generate other `@link` directive uses
```
