### ISSUE TITLE
0.1.0 Roadmap

### ISSUE THREAD

**Issue by lrlna** [apollographql/apollo-rs#81]
## Description
This is a checklist for items we'd like to include and have done in the initial release of `apollo-rs`. 

### Checklist
- [x] Parser is spec compliant, #8 
- [ ] Parser provides useful errors, https://github.com/apollographql/apollo-rs/issues/70, https://github.com/apollographql/apollo-rs/issues/72, https://github.com/apollographql/apollo-rs/issues/73
- [x] Parser is decently well tested, https://github.com/apollographql/apollo-rs/issues/67.
- [ ] We are able to go: SDL input -> AST -> SDL, this requires incorporating https://github.com/apollographql/apollo-rs/issues/61
- [ ] We have `usage`, `contributing`, `development` docs. This should include why decided to build this project from scratch, as there are already existing Rust graphql parsers out there. https://github.com/apollographql/apollo-rs/issues/76, https://github.com/apollographql/apollo-rs/issues/77, https://github.com/apollographql/apollo-rs/issues/78
- [x] We have a CI, https://github.com/apollographql/apollo-rs/issues/74
- [x] We have a strategy for managing the issue tracker
- [ ] We have some benchmarks against existing Rust graphql parsers (and also probably the javascript one), https://github.com/apollographql/apollo-rs/issues/75
- [x] We should create detailed issues on next projects/crates `apollo-rs` will be tackling.

### Nice to have
- [ ] `fuzzer` to ensure spec compliance, and correct error management https://github.com/apollographql/apollo-rs/issues/59, https://github.com/apollographql/apollo-rs/issues/60

### Excluded from this release
- This release will not come with execution
- This release will not come with graphql validation
- This release will not come with higher level schema representation

**Comment by lrlna** [comment]
we released 0.1.0 of the `apollo-parser` back in November! closing this
